root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 2020
  sourceType: "module"
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
rules:
  "@typescript-eslint/strict-boolean-expressions": "off"
  "@typescript-eslint/no-non-null-assertion": "off"

