root: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json" # Path to the TypeScript config file
  ecmaVersion: 2020
  sourceType: "module"
plugins:
  - "@typescript-eslint"
  - prettier
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
